### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by OsaPL** [VirtualEngine/LegacyNetworking#1]
Continues from: [Lability #376](https://github.com/VirtualEngine/Lability/issues/376)

Win7SP1 machines configures normally, and is fully functional, but when I try to use LegacyNetworking components I'm getting "You cannot call a method on a null-valued expression."

Including log, and Cfg.ps1 with cfgdata.psd1

[bootstrap.log](https://github.com/VirtualEngine/LegacyNetworking/files/3669582/bootstrap.log)
[Resources.zip](https://github.com/VirtualEngine/LegacyNetworking/files/3669608/Resources.zip)

**Comment by iainbrighton** [comment]
@OsaPL Quick question - are you sure that the NIC is called `Ethernet` and not `Local Area Connection` (or similar)?

**Comment by OsaPL** [comment]
I missed such a crucial detail, I feel really stupid. 
Anyways, thanks a lot now it works perfectly. :)
